topic:
  version: v1
  prefix: ${spring.application.name}
  orders: ${topic.prefix}.orders.${topic.version}
spring:
  main:
    web-application-type: none
    banner-mode: off
    log-startup-info: false
  application:
    name: kafka-offsets
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: ${spring.application.name}-consumer-id
      group-id: ${spring.application.name}-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: read_committed
      enable-auto-commit: true
      auto-commit-interval: 1s
      max-poll-records: 10
      properties:
        auto:
          offset:
            reset: earliest
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      client-id: ${spring.application.name}-producer-id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: batch
      client-id: ${spring.application.name}-listener-id
      log-container-config: true
      missing-topics-fatal: true
      concurrency: 1
    template:
      default-topic: ${topic.orders}
logging:
  level:
    org:
      springframework:
        kafka:
          config:
            StreamsBuilderFactoryBean: debug
          listener: trace
      apache:
        kafka: info
    adrhc:
      go:
        ro: debug

