spring:
  main:
    web-application-type: none
    banner-mode: off
    log-startup-info: false
  application:
    name: kafka-offsets
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: ${spring.application.name}-consumer-id
      group-id: ${spring.application.name}-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: read_committed
      enable-auto-commit: true
      auto-commit-interval: 1d
      max-poll-records: 10
      properties:
        auto:
          offset:
            reset: earliest
    producer:
      client-id: ${spring.application.name}-producer-id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
topic:
  version: v1
  prefix: ${spring.application.name}
  orders: ${topic.prefix}.orders.${topic.version}
logging:
  level:
    org:
      springframework:
        kafka:
          config:
            StreamsBuilderFactoryBean: debug
          listener: info
      apache:
        kafka: info
    ro:
      go:
        adrhc: debug

